### ISSUE TITLE
Problem with output format

### ISSUE THREAD

**Issue by overthink** [mdsherry/sortable_matcher#1]

**Comment by overthink** [comment]
Whoops, I'm just clicking submit on everything -- sorry!

Anyway, there is a problem with the output format for your solution.  Please make sure each line in the output is a valid JSON document matching the result object described at http://sortable.com/challenge/.  Right now it looks like output is one giant JSON object with product names as keys.

I aslo noticed --listings and --products don't seem to work.  My invocation was `./reconcile.py --products ../products.txt --listings ../listings.txt --output results.txt`

Works fine if the files are in the same dir as reconcile.py.

Thanks!

Mark from Sortable

**Comment by overthink** [comment]
Whoops, I'm just clicking submit on everything -- sorry!

Anyway, there is a problem with the output format for your solution. Please make sure each line in the output is a valid JSON document matching the result object described at http://sortable.com/challenge/. Right now it looks like output is one giant JSON object with product names as keys.

I also noticed --listings and --products don't seem to work. My invocation was ./reconcile.py --products ../products.txt --listings ../listings.txt --output results.txt

Works fine if the files are in the same dir as reconcile.py.

Thanks!

Mark from Sortable

**Comment by mdsherry** [comment]
Hi Mark,

I've fixed the output. It should now be one JSON object per line.

I'm unable to reproduce your problems with --listings and --products. What error are you seeing?

**Comment by overthink** [comment]
Hey Mark.

Output fixes worked.  Thanks.

Bad bug report by me.  Here's a simpler repro: (of note, I don't need this fixed, just letting you know)

$ ./reconcile.py --help
Traceback (most recent call last):
  File "./reconcile.py", line 242, in <module>
    args = parser.parse_args()
  File "/usr/lib/python2.7/argparse.py", line 1688, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1710, in parse_known_args
    default = self._get_value(action, default)
  File "/usr/lib/python2.7/argparse.py", line 2239, in _get_value
    raise ArgumentError(action, msg)
argparse.ArgumentError: argument --listings: can't open 'listings.txt': [Errno 2] No such file or directory: 'listings.txt'

It's the type=argparse.FileType('rt') stuff, but I didn't investigate why.  This is an old python: 2.7.3.
